version: "3.8"

services:
  api-dev:
    build:
      context: ./api
    environment:
      DATABASE_PATH: ${DATABASE_PATH}
      SESSION_SECRET: ${SESSION_SECRET}
      MEDIA_PATH: /media
      NODE_ENV: ${NODE_ENV}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: "Вопли <noreply@vopley.net>"

    volumes:
      - appdata-dev:/data
      - media-dev:/media
    expose:
      - "3000"

  media-dev:
    image: nginx:alpine
    volumes:
      - media-dev:/media:ro
      - ./media-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"

  nginx-dev:
    image: nginx:alpine
    depends_on:
      - api-dev
      - media-dev
    ports:
      - "3006:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - webdist-dev:/usr/share/nginx/html:ro

  web-build-dev:
    build:
      context: ./web
    volumes:
      - webdist-dev:/out
    command: sh -c "rm -rf /out/* && cp -r /app/dist/* /out/"

volumes:
  appdata-dev:
  webdist-dev:
  media-dev:
